class Lottery
	def lucky_number
		lucky = rand 1..36
	end

	def create_ticket
		ticket = Array.new()
		$i = 0
		while $i < 6 do
			n = lucky_number			#e.g 12 randomly generated
			if ticket.include?(n)		
				#puts "#{n} exists"			# if true means 12 already exists in the array
			else
				#puts "#{n} new"		# if not it is a new item
				ticket.push(n)			# then add it to the array
				$i += 1
			end
		end
		ticket.sort!					#sort array ascending
		puts "Here is your 6 lucky numbers generated by the courtesy of Ruby"
		puts ticket
	end


end

ticket = Lottery.new
ticket.create_ticket()
